project:
  type: website

website:
  title: "Redes Neuronales Artificiales y Algoritmos Bioinspirados"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/RNA-y-Algo-Bioinsp-2024-02/blog

format:
  html:
    theme:
     light: flatly
     dark: darkly
    css: styles.css
    toc: true
    toc-location: left
    code-fold: true
    code-tools: true

editor: visual


